
import = ["~/.config/alacritty/colors/catppuccin-macchiato.toml",]

[window]

opacity = 0.95

padding.x = 5
padding.y = 5

decorations = "None"
decorations_theme_variant = "Dark" # "Dark"

[font]

normal = {family = "FiraMono Nerd Font", style = "Medium"}
bold = {family = "FiraMono Nerd Font", style = "Bold"}
italic = {family = "FiraMono Nerd Font", style = "Italic"}
bold_italic = {family = "FiraMono Nerd Font", style = "Bold Italic"}

size = 12.0

[keyboard]
bindings = [
	{key = "v", mods = "Control", action = "Paste"},
	{key = "Back", mods = "Control", chars = "\u0017"},
]

